apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.credentials_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  users-config: |
    {{ .Values.storage.credentials | toJson }}
